services:
  nginx:
    image: nginx:mainline-alpine3.23-slim
    container_name: my_nginx
    ports:
      - 3000:80
  react_app:
    image: nopcommerceteam/nopcommerce:4.90.3
    restart: always
    pull_policy: build
    container_name: my_react_app
    ports:
      - 8080:80
