services:
  wordpress:
    image: wordpress:php8.1-apache
    container_name: wordpress-srv
    networks:
      - wordpress_network
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress-data:/var/www/html
  mysql:
    container_name: mysql-srv
    image: mysql:8.0.44-debian
    networks:
      - wordpress_network
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER:- exampleuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:- somerootpassword}
    volumes:
      - db-data:/var/lib/mysql
volumes:
  wordpress-data:
  db-data:
networks:
  wordpress_network:
  default:
    driver: bridge
